name: playground-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipython
  - pip
  - scikit-learn
  - pip:
    - librosa
    - pydub
    - soundfile
    - tqdm
